//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOP_Community.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monthly_Due
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Monthly_Due()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int id { get; set; }
        public Nullable<decimal> monthlyFee { get; set; }
        public string month { get; set; }
        public Nullable<System.DateTime> dueDate { get; set; }
        public Nullable<int> createdBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
