//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOP_Community.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int id { get; set; }
        public Nullable<int> monthly_Due { get; set; }
        public Nullable<int> transactedBy { get; set; }
        public Nullable<int> resident { get; set; }
        public Nullable<bool> paidStatus { get; set; }
        public Nullable<System.DateTime> paidDate { get; set; }
    
        public virtual Monthly_Due Monthly_Due1 { get; set; }
        public virtual Resident Resident1 { get; set; }
        public virtual User User { get; set; }
    }
}
